# Generated by Django 4.1.1 on 2023-01-07 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_code', models.CharField(max_length=1024)),
                ('course_title', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=1024)),
                ('ext', models.CharField(max_length=1024)),
                ('size', models.FloatField()),
                ('url', models.CharField(max_length=1024)),
                ('pic_url', models.CharField(max_length=1024)),
                ('upload_by', models.IntegerField()),
                ('upload_at', models.DateTimeField()),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('last_download_at', models.DateTimeField()),
                ('last_download_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('upload_num', models.IntegerField()),
                ('download_num', models.IntegerField()),
                ('downloadable_count', models.IntegerField(default=10)),
                ('total_upvote', models.IntegerField()),
                ('total_downvote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.IntegerField()),
                ('val', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.file')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.IntegerField()),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.file')),
            ],
        ),
    ]
